# Site settings
title: "Mohammad Ghazanfari"

# Resume settings
name:             "Mohammad Ghazanfari"
email:            "mgh5225@gmail.com"
# logo:             "assets/img/logo.png"
social_links:
  github_url:            "https://github.com/mgh5225"
  linkedin_url:          "https://www.linkedin.com/in/mohammad-ghazanfari"